//ejemplo2_16.c
#include <stdio.h>
#include <stdlib.h>

int main (){
    float f=4.0/3.0;
    double d=4.0/3.0;
    f=(f-1)*4;
    printf("Iteración  1=%f\n",f);
    f=(f-1)*4;
    printf("Iteración  2=%f\n",f);
    f=(f-1)*4;
    printf("Iteración  3=%f\n",f);
    f=(f-1)*4;
    printf("Iteración  4=%f\n",f);
    f=(f-1)*4;
    printf("Iteración  5=%f\n",f);
    f=(f-1)*4;
    printf("Iteración  6=%f\n",f);
    f=(f-1)*4;
    printf("Iteración  7=%f\n",f);
    f=(f-1)*4;
    printf("Iteración  8=%f\n",f);
    f=(f-1)*4;
    printf("Iteración  9=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 10=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 12=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 13=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 14=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 15=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 16=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 17=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 18=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 19=%f\n",f);
    f=(f-1)*4;
    printf("Iteración 20=%f\n",f);

    d=(d-1)*4;
    printf("Iteración  1=%f\n",d);
    d=(d-1)*4;
    printf("Iteración  2=%f\n",d);
    d=(d-1)*4;
    printf("Iteración  3=%f\n",d);
    d=(d-1)*4;
    printf("Iteración  4=%f\n",d);
    d=(d-1)*4;
    printf("Iteración  5=%f\n",d);
    d=(d-1)*4;
    printf("Iteración  6=%f\n",d);
    d=(d-1)*4;
    printf("Iteración  7=%f\n",d);
    d=(d-1)*4;
    printf("Iteración  8=%f\n",d);
    d=(d-1)*4;
    printf("Iteración  9=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 10=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 11=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 12=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 13=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 14=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 15=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 16=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 17=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 18=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 19=%f\n",d);
    d=(d-1)*4;
    printf("Iteración 20=%f\n",d);
    system("PAUSE");
}
